ci: fix translation download

diff --git a/.github/workflows/crowdin-export.yml b/.github/workflows/crowdin-export.yml
--- a/.github/workflows/crowdin-export.yml
+++ b/.github/workflows/crowdin-export.yml
@@ -14,16 +14,35 @@ jobs:
               with:
                   fetch-depth: 1
                   token: ${{secrets.GITHUB_TOKEN}}
+
             - name: Test using Node.js
               uses: actions/setup-node@v6
               with:
                   node-version: "lts/*"
+
             - name: Install dependencies
               run: npm install
+
             - name: Export translations
-              run: npx ts-node --project ./tsconfig.node.json ./script/crowdin/export-translation.ts
+              run: |
+                  npx ts-node --project ./tsconfig.node.json ./script/crowdin/export-translation.ts 2>&1 | tee /tmp/export-output.log
+                  exit ${PIPESTATUS[0]}
+              continue-on-error: true
+
+            - name: Check exporting logs
+              if: always()
+              run: |
+                  if grep -q "[CROWDIN-ERROR]" /tmp/export-output.log; then
+                    echo "::error:: Found errors in export logs"
+                    exit 1
+                  else
+                    echo "No errors found in export logs"
+                  fi
+
             - name: Test typescript
+              if: success()
               run: npx tsc --noEmit
+
             - name: Create Pull Request
               if: success()
               uses: peter-evans/create-pull-request@v8
